# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

## dependencies that need to be installed beforehand if any
sudo: true
before_install:
  - sudo apt-get install jags
  - sudo apt-get install r-cran-rjags
